### ISSUE TITLE
Indices in javascript schema

### ISSUE THREAD

**Issue by oskr** [typeorm/javascript-example#2]
Hello, Is there any way to create indices in the javascript schema?
This feature is documented only with decorators but I tried 

```javascript
module.exports = {
    name: "Category",
    columns: {
        id: {
            primary: true,
            type: "int",
        },
        name: {
            index: true,
            type: "string"
        }
    }
};
```

Also tried
```javascript
...
name:{
       index:{
             name: "INAME"
       }
}
...
```
or with the property indices in the root schema:
```javascript
...
name: "Category",
indices:[
         {
              name: "INAME",
              columns: ["name"]
         }
]
...
```

Is this feature supported on javascript schemas or only for typescript using decorators?

**Comment by pleerock** [comment]
@iz-iznogood is this supported now?

**Comment by iz-iznogood** [comment]
Yrs it is supported. Check the EntitySchema and EntitySchemaIndex
